name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]  # Triggers on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Setup PHP for Laravel
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Adjust to your PHP version
        extensions: mbstring, intl, pdo_mysql
    
    # Setup Node.js for React
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjust to your Node.js version
        cache: 'npm'
        cache-dependency-path: 'prebuilds_frontend/package-lock.json'
    
    # Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./prebuilds_frontend
      run: npm ci
    
    # Build Frontend
    - name: Build Frontend
      working-directory: ./prebuilds_frontend
      run: npm run build
    
    # Deploy via SSH
    - name: Deploy to Hostinger
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        script: |
          # Backend Deployment
          cd ~/domains/api.prebuilds.shop
          git pull origin main
          
          # Install Composer dependencies
          composer install --no-dev --optimize-autoloader
          
          # Run Laravel migrations (optional, uncomment if needed)
          # php artisan migrate --force
          
          # Clear Laravel caches
          php artisan config:clear
          php artisan cache:clear
          
          # Frontend Deployment
          cd ~/domains/prebuilds.shop/public_html
          
          # Remove existing frontend files
          rm -rf assets index.html *.svg *.png *.ico
          
          # Copy new build files from GitHub Actions
          cp -R $GITHUB_WORKSPACE/prebuilds_frontend/dist/* .
          
          # Ensure symlink to Laravel public is maintained
          ln -sf ../../api.prebuilds.shop/public public