name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          # Add the SSH private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start the SSH agent
          eval $(ssh-agent -s)

          # Add the SSH key with passphrase (assuming passphrase is stored in GitHub secrets)
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          timeout: 2m
          command_timeout: 2m
          script: |
            echo "Deployment Started"
            whoami
            pwd
            
            # Navigate to your project directory on Hostinger
            cd /home/u824026742/domains/PreBuilds
            
            # Load your shell profile to ensure environment variables are set
            source ~/.bashrc || true
            source ~/.profile || true
            
            # Add common Node.js installation paths to PATH
            export PATH="$HOME/bin:$HOME/.local/bin:$HOME/node/bin:$HOME/.nvm/versions/node/*/bin:$PATH"
            
            # Debugging - print paths and check for npm
            echo "PATH: $PATH"
            which npm || echo "npm not found in PATH"
            
            # Execute the deploy.sh script with the correct shell to ensure environment is loaded
            echo "Executing deploy.sh script..."
            bash -l ./deploy.sh || { echo "Deploy failed!"; exit 1; }
            
            echo "Deployment Completed"