name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 65002 ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
        # Setting the SSH passphrase environment variable
        export SSH_ASKPASS='/usr/bin/ssh-askpass'
        export DISPLAY=:0
        ssh-add <(echo "$SSH_PASSPHRASE")

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: 65002
        timeout: 2m
        command_timeout: 2m
        script: |
          echo "Deployment Started"
          whoami
          pwd
          echo "Current Directory Contents:"
          ls -la
          # Execute your deploy script
          ./deploy.sh
