name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key with passphrase
      run: |
        # Create .ssh directory
        mkdir -p ~/.ssh

        # Set up the private key from GitHub secrets
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Start SSH agent
        eval $(ssh-agent -s)

        # Add the private key with the passphrase
        echo "$SSH_PASSPHRASE" | ssh-add - <<< "$SSH_PRIVATE_KEY"
        
        # Ensure that the host is added to known hosts to avoid SSH warnings
        ssh-keyscan -p 65002 ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: 65002
        timeout: 2m
        command_timeout: 2m
        script: |
          echo "Deployment Started"
          whoami
          pwd
          echo "Current Directory Contents:"
          ls -la
          # Execute your deploy script
          ./deploy.sh
